# Generated by Django 2.0 on 2018-07-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
